name: Release OptimizedPlus

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
env:
  GITHUB_API_TOKEN: ${{secrets.API_TOKEN}}
  MODRINTH_API_TOKEN: ${{secrets.MODRINTH_API_TOKEN}}

jobs:
  build:
    name: "Release"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun Action
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install

      - name: Run Script
        run: bun run script.js
